// GET MEALS
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const LOADING_MEALS = "LOADING_MEALS";
export const GET_MEALS_ERROR = "GET_MEALS_ERROR";

// CART
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
