// GET MEALS
export const GET_MEALS_SUCCESS = "GET_MEALS_SUCCESS";
export const LOADING_MEALS = "LOADING_MEALS";
export const GET_MEALS_ERROR = "GET_MEALS_ERROR";

// CART + EDIT ITEMS
export const OPEN_CART_MODAL = "OPEN_CART_MODAL";
export const CLOSE_CART_MODAL = "CLOSE_CART_MODAL";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";

// OPEN FORM
export const START_CHECKOUT = "START_CHECKOUT";

// SUBMIT ORDER
export const ORDER_LOADING = "ORDER_LOADING";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDER_CLEAR = "ORDER_CLEAR";
